<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AchievementLabs.Enhancements/AchievementLabs.Enhancements.csproj" />
    <ProjectReference Include="../../src/AchievementLabs.Desktop/AchievementLabs.Desktop.csproj" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <None Update="*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
